// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBe2HNJfEXU3zUAD4T6NNOHfKw5puhXeE',
    appId: '1:562166694361:web:d7a66a46c92410a77919c8',
    messagingSenderId: '562166694361',
    projectId: 'conversate-10bdb',
    authDomain: 'conversate-10bdb.firebaseapp.com',
    storageBucket: 'conversate-10bdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsc8jz8B8Q6ZUg0Emzaz4zXtl8dfx1vjU',
    appId: '1:562166694361:android:de2b71023dd19a447919c8',
    messagingSenderId: '562166694361',
    projectId: 'conversate-10bdb',
    storageBucket: 'conversate-10bdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC52r1V4MWIjBtQpYlFG0UoGJ_87pPPaoU',
    appId: '1:562166694361:ios:21de8a39d1f918957919c8',
    messagingSenderId: '562166694361',
    projectId: 'conversate-10bdb',
    storageBucket: 'conversate-10bdb.appspot.com',
    iosBundleId: 'com.example.converse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC52r1V4MWIjBtQpYlFG0UoGJ_87pPPaoU',
    appId: '1:562166694361:ios:21de8a39d1f918957919c8',
    messagingSenderId: '562166694361',
    projectId: 'conversate-10bdb',
    storageBucket: 'conversate-10bdb.appspot.com',
    iosBundleId: 'com.example.converse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBe2HNJfEXU3zUAD4T6NNOHfKw5puhXeE',
    appId: '1:562166694361:web:8a3800726a789a1b7919c8',
    messagingSenderId: '562166694361',
    projectId: 'conversate-10bdb',
    authDomain: 'conversate-10bdb.firebaseapp.com',
    storageBucket: 'conversate-10bdb.appspot.com',
  );
}
